### ISSUE TITLE
Version inconsistency

### ISSUE THREAD

**Issue by victorengel** [PolymathNetwork/polymath.js-deprecated#72]
https://github.com/PolymathNetwork/polymath.js/releases/tag/v0.1.0 says version 0.1.0 but package was updated to 1.0.0.

**Comment by priom** [comment]
no it says 0.2.0... https://www.npmjs.com/package/polymathjs

**Comment by victorengel** [comment]
Follow my link. It says 0.1.0. Yes, I also see 0.2.0. And I also see 1.0.0. That's the point. The versions are inconsistent. One is the readme (what I linked). One is in package-lock.json. One is in package.json.

**Comment by ChainSafeSystems** [comment]
Everything has been updated #73.
